# Product
components:
 schemas:
   Product:
     type: object
     required:
       - _id
       - title
       - price
       - description
       - photo
       - category
     properties:
       _id:
         type: string
         description: Id del Producto.
       title:
         type: string
         description: Nombre del Producto.
       price:
         type: number
         description: Precio del Producto.
       description:
         type: string
         description: Descripción del Producto.
       photo:
         type: string
         description: Imagen del Producto.
       category:
         type: string
         description: Categoria del Producto.         
     example:
        id: 4ughd73658fnsk85dh58sk
        title: Samsung A31
        price: 30000
        description: Celular Copado
        photo: celular.png
        prcategoryice: celulares